// import { SQLDatabase } from 'encore.dev/storage/sqldb';
// import knex from 'knex';

// // Define a database named 'appDB', using the database migrations
// // in the "./migrations" folder. Encore automatically provisions,
// // migrates, and connects to the database.
// const DB = new SQLDatabase('appDB', {
//   migrations: './migrations',
// });

// // Use Knex.js to connect to the database
// const ORM = knex({
//   client: 'pg',
//   connection: DB.connectionString,
// });

// export const databaseProviders = [
//   {
//     provide: 'DATABASE_CONNECTION',
//     useFactory: async () => ORM,
//   },
// ];



import { SQLDatabase } from "encore.dev/storage/sqldb";
import { PrismaClient } from "@prisma/client";

// Define a database named 'encore_prisma_test', using the database migrations
// in the "./prisma/migrations" folder (where prisma will generate their migrations).
// Set `source` to `prisma` to let Encore know that the migrations are generated by Prisma.
const DB = new SQLDatabase('encore_prisma_test', {
  migrations: {
    path: './prisma/migrations',
    source: 'prisma',
  },
});

// Setup prisma client with connection string
const prisma = new PrismaClient({
  datasources: {
    db: {
      url: DB.connectionString,
    },
  },
});

export const databaseProviders = [
  {
    provide: 'DATABASE_CONNECTION',
    useFactory: async () => prisma,
  },
];

